spring.application.name=bubble
server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/${DATABASE_NAME:db-name}
spring.datasource.username=${DATABASE_USER:db-user}
spring.datasource.password=${DATABASE_PASSWORD:db-password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=5000
spring.thymeleaf.cache=false